In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({'text':['people watch cridket' , 'player was player' ,
'people write comment','cricket play comment' ] , 'output ': [1,1,0,0]})

In [5]:
df

                   text  output
0  people watch cridket        1
1     player was player        1
2  people write comment        0
3  cricket play comment        0

In [6]:
from sklearn. feature_extraction.text import CountVectorizer

In [7]:
cv = CountVectorizer()

In [8]:
bow = cv. fit_transform(df['text'])

# vocab
print(cv.vocabulary_)

{'people': 3, 'watch': 7, 'cridket': 2, 'player': 5, 'was': 6, 'write': 8, 'comment': 0, 'cricket': 1, 'play': 4}

In [9]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 1 0 0 0 1 0]]
[[0 0 0 0 0 2 1 0 0]]

In [10]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 0, 1, 1]])

# 2.N-grams

In [14]:

v = CountVectorizer(ngram_range=(1, 2))
# v = CountVectorizer(ngram_range=(2, 2))

In [15]:
bow = v.fit_transform(df['text'])

In [16]:
df['text']

0    people watch cridket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [17]:
print(v.vocabulary_)

{'people': 4, 'watch': 13, 'cridket': 3, 'people watch': 5, 'watch cridket': 14, 'player': 9, 'was': 11, 'player was': 10, 'was player': 12, 'write': 15, 'comment': 0, 'people write': 6, 'write comment': 16, 'cricket': 1, 'play': 7, 'cricket play': 2, 'play comment': 8}

In [18]:
# TF(Term Frequencey)
# 2. IDF(Inverse Document Frequencey)

# TF(t,d) = (Number of occurences of term t in document d)/
# (Total number of terms in the document d)
# example == >
# d1 = people watch cricket .

# tf(people,d1) = 1/3

# d2 = match was match.
# tf(match , d2) = 2/3

In [20]:
# IDF(t) = Loge(Total number of documents in the corpus)/
# (Number of documents with term t in them)
# here corpus means number of sentences

# Example == >
# d1 = people watch cricket .
# d2 = cricket was cricket .
# d3 = people write comment .
# d4 = cricket write comment .

# idf(cricket) = Log(4/4)
# idf(people) = Log(4/2)

# we can use this by apply feature_extraction method in sklearn

In [21]:
df

                   text  output
0  people watch cridket        1
1     player was player        1
2  people write comment        0
3  cricket play comment        0

In [22]:
from sklearn. feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.61761437, 0.48693426, 0.        ,
        0.        , 0.        , 0.61761437, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.89442719, 0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.        , 0.52640543, 0.        ,
        0.        , 0.        , 0.        , 0.66767854],
       [0.48693426, 0.61761437, 0.        , 0.        , 0.61761437,
        0.        , 0.        , 0.        , 0.        ]])

In [23]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.91629073 1.91629073 1.51082562 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073]
['comment' 'cricket' 'cridket' 'people' 'play' 'player' 'was' 'watch'
 'write']